### PR TITLE
Update to bukkit 1.8 and add reload command.

### PR DESCRIPTION
**Pull request by 1stGlitch**
I am a fan of this plugin so I updated it to bukkit/spigot 1.8 and I added/changed a few minor things in the process (like I added a reload command). I also rewrote how the plugin decides where to place the fake entities mostly because I could not get the old system working and I feel that the new system is simpler to update in the future! 

If you are no longer interested in maintaining this plugin then I can take over if that is something that you are interested in.

I've compiled and tested many times, it works. (In fact I am using it on my server right now!)

That's all for now!
1stGlitch

### CODE REVIEW

**Comment by maciekmm** [comment]
Hello,
thanks for being interested. This was a really small plugin written only for one user on spigot that wanted something as simple as that, it turned out to be more needed. This plugin from the beginning was badly coded, due to the architecture.

Regarding PR:
I'm not a fan of iterating through online players, using depreceted function is just fine, although matchPlayers() would be better.

**Comment by 1stGlitch** [comment]
It may have started as a small plugin but with over 1000 downloads on the spigot forums and almost 5000 on the bukkit forums I think it's safe to say that server admins want it! I changed the code in my most recent commit so it does not iterate through all the players anymore and uses the matchPlayers() method just for fun I also made it so if multiple names are found it allows to you choose which one you want by clicking on it in chat. (screenshot below)

My offer to maintain the plugin for you is still on the table if you're interested!

-1stGlitch

**Comment by maciekmm** [comment]
Thanks,
also dunno if would happen (needs testing), but if we have two players -> eg. abc and abcd
if someone types abc it should check abc and not display abcd, for the reason of remote command executors. Other solution may be checking if command sender is instantiated from a Player object.

Last little minor improvement you can do is to instantiate Random outside of the getName method. 

Write me a mail - business@maciekmm.net with your bukkit username so I can pass you management rights.

**Comment by 1stGlitch** [comment]
Hello,
I already tested that before I made that commit, I had 2 players (1 in offline mode) named "1stGlitch" and "1stGlitch1" when I did /auracheck 1stGlitch it successfully ran without asking which player to run it for, this must be a built in feature to matchPlayers().

I'm sure you meant to write the newName method, in my most recent commit I only instantiate Random once, outside of any method, if you meant something else let me know. I also found a bug where if you right click on the entities they die, so I added to a check to make sure that you are actually attacking the entity.

1 last thing I did is change (in the getSpawnWrapper() method) how the WrappedDataWatcher sets the values, I changed it back to how you originally had it to simplify the code, i'm not sure why I even touched that in the first place. Anyways I've tested it many times under different circumstances so it definitely all works in practice, if you find any other issues just let me know!

Sending email now!

-1stGlitch

**Pull request merged**
